export const data = {
  cron: null,
  endTime: null,
  jobId: 15288,
  jobName: 'aps.bank',
  jobType: 3,
  ownerNames: 'xxx',
  state: '测试',
  scheduleTime: null,
  taskId: null,
  jobTypeCn: 'SQL',
  childrenList: [{
    cron: null,
    endTime: null,
    jobId: 15281,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: '测试',
    scheduleTime: null,
    taskId: null,
    jobTypeCn: 'SQL'
  }, {
    cron: null,
    endTime: null,
    jobId: 15282,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: '测试',
    scheduleTime: null,
    taskId: null,
    jobTypeCn: 'SQL'
  }, {
    cron: null,
    endTime: null,
    jobId: 15283,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: '测试',
    scheduleTime: null,
    taskId: null,
    jobTypeCn: 'SQL'
  }, {
    cron: null,
    endTime: null,
    jobId: 15284,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: '测试',
    scheduleTime: null,
    taskId: null,
    jobTypeCn: 'SQL'
  }],
  parentList: [{
    cron: null,
    endTime: null,
    jobId: 15285,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: null,
    scheduleTime: null,
    taskId: null
  }, {
    cron: null,
    endTime: null,
    jobId: 15286,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: null,
    scheduleTime: null,
    taskId: null
  }, {
    cron: null,
    endTime: null,
    jobId: 15287,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: null,
    scheduleTime: null,
    taskId: null
  }, {
    cron: null,
    endTime: null,
    jobId: 15289,
    jobName: 'aps.bank',
    jobType: 3,
    ownerNames: 'xxx',
    state: null,
    scheduleTime: null,
    taskId: null
  }]
}
